"""add custom name to contacts

Revision ID: 668d0e5321c7
Revises: 8bf99494038d
Create Date: 2026-09-21 19:27:21.636685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668d0e5321c7'
down_revision: Union[str, Sequence[str], None] = '8bf99494038d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
